apiVersion: v1
kind: Service
metadata:
  name: conversao-service
spec:
  selector:
    app: conversao
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
  
# k3d cluster create clusterconversao --servers 1 --agents 1 -p "8080:30000@loadbalancer"
# kubectl apply -f .\k8s\web\deployment.yaml